export enum AppNavigationState {
    SLIDE_RIGHT = 'SLIDE_RIGHT',
    SLIDE_LEFT = 'SLIDE_LEFT',
    SLIDE_LEFT_FROM_CENTER ="SLIDE_LEFT_FROM_CENTER",
    SLIDE_LEFT_FROM_RIGHT = "SLIDE_LEFT_FROM_RIGHT",
    SLIDE_RIGHT_FROM_CENTER ="SLIDE_RIGHT_FROM_CENTER",
    SLIDE_RIGHT_FROM_LEFT = "SLIDE_RIGHT_FROM_LEFT",
    CENTER = 'CENTER',
    UNDEFINED = 'UNDEFINED'
}